feetech_ros2_interface:
  ros__parameters:
    node:
      frequency: 10.0

    driver:
      port_name: "/dev/ttyUSB0"
      baud_rate: 1000000
      frequency: 100.0

    servos:
      ids: [11, 32, 13] #, 2, 3, 4, 5, 6, 7, 8]
      operating_modes: [4, 4, 4] # Velocity mode 2, continuous position mode 4
      homing_modes: [0, 0, 0] #, 0, 0, 0, 0, 0, 0, 0]
      max_speeds: [1.0, 1.0, 1.0] #, 100., 100., 100., 100., 100., 100., 100.]
      max_currents: [100., 100., 100.] #, 100., 100., 100., 100., 100., 100., 100.]
      gear_ratios: [4.0, 1.0, 2.0]
