version: "3.8" # Docker version

# Builds the image from the Dockerfile
services:
  aerial-tactile-servoing-controller:
    build: ../
    privileged: true
    network_mode: 'host'
    command: serial --dev /dev/ttyACM0 -b 921600 # Look up what this means