version: "3.8" # Docker version
services:
  # Service 1
  service1:
    image: service1:latest
    container_name: service1
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - service2