/feetech_ros2_interface:
  ros__parameters:
    node:
      frequency: 25.0

    driver:
      port_name: "/dev/ttyUSB0"
      baud_rate: 115200
      frequency: 50.0
      logging: False

    servos:
      ids: [11, 32, 13] #, 2, 3, 4, 5, 6, 7, 8]
      operating_modes: [4, 4, 4] # Velocity mode 2, continuous position mode 4
      homing_modes: [0, 0, 0] #, 0, 0, 0, 0, 0, 0, 0]
      directions: [-1, -1, -1] #,
      max_speeds: [0.35, 0.35, 0.35] # rad/s
      max_currents: [100., 100., 100.] #, 100., 100., 100., 100., 100., 100., 100.]
      gear_ratios: [4.0, 1.0, 2.0]
      proportional_gains: [0.3, 0.1, 0.2]
      derivative_gains: [0.1, 0.03, 0.03]
      integral_gains: [0.0, 0.0, 0.0]